development:
   adapter: mysql
   database: jukebox_development
   username: root
   password: WNMWMWAMmk3
   host: localhost

test:
   adapter: mysql
   database: jukebox_test
   username: root
   password: WNMWMWAMmk3
   host: localhost
   
production:
   adapter: mysql
   database: jukebox_production
   username: root
   password: WNMWMWAMmk3
   host: localhost
